### PR TITLE
Create HOWTO_install_blazegraph_in_docker.markdown

### PR DESCRIPTION
**Pull request by HNieme**

### CODE REVIEW

**Comment by quasarchimaere** [comment]
not sure if this is the proper place for this rather unrelated howto, maybe we can merge this into our main repo instead, @fkleedorfer what do you think?

**Comment by fkleedorfer** [comment]
@quasarchimaere yes maybe best to have everything in one place, so that would be https://github.com/researchstudio-sat/webofneeds/tree/master/documentation  - this is also true for setup_mac.md

**Comment by quasarchimaere** [comment]
also i am pretty sure there is a prepacked docker image for blazegraph on dockerhub already so i think there is no need in packing it ourselves

**Comment by quasarchimaere** [comment]
please move this to this directory/repository:

https://github.com/researchstudio-sat/webofneeds/blob/master/documentation/howto/README.md

**Pull request closed without merging**
